/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#c4e7ff",
        surface: "#0e1321",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#004c69",
        "tertiary-container": "#009bd1",
        "surface-bright": "#343948",
        "on-secondary-container": "#c4abff",
        "on-secondary": "#3c0091",
        "on-secondary-fixed-variant": "#5516be",
        "primary-fixed": "#d8e2ff",
        "surface-tint": "#adc6ff",
        "secondary-fixed": "#e9ddff",
        "surface-dim": "#0e1321",
        "on-surface-variant": "#c2c6d6",
        "surface-container-low": "#161b29",
        "inverse-surface": "#dee2f6",
        tertiary: "#7bd0ff",
        "on-tertiary-fixed": "#001e2c",
        "on-error-container": "#ffdad6",
        "secondary-container": "#571bc1",
        "outline-variant": "#424754",
        "on-secondary-fixed": "#23005c",
        "on-tertiary-container": "#002d40",
        "on-primary-container": "#00285d",
        error: "#ffb4ab",
        "tertiary-fixed-dim": "#7bd0ff",
        background: "#0e1321",
        "surface-container": "#1a1f2e",
        "surface-container-highest": "#2f3444",
        "error-container": "#93000a",
        "on-primary": "#002e6a",
        "surface-container-lowest": "#090e1b",
        primary: "#adc6ff",
        "primary-fixed-dim": "#adc6ff",
        "inverse-primary": "#005ac2",
        "on-tertiary": "#00354a",
        "secondary-fixed-dim": "#d0bcff",
        "inverse-on-surface": "#2b303f",
        "on-primary-fixed-variant": "#004395",
        "surface-variant": "#2f3444",
        "on-primary-fixed": "#001a42",
        secondary: "#d0bcff",
        "surface-container-high": "#252a38",
        "on-background": "#dee2f6",
        "primary-container": "#4d8eff",
        outline: "#8c909f",
        "on-surface": "#dee2f6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "gutter-mobile": "0.5rem",
        "space-lg": "1.25rem",
        "space-xl": "2rem",
        "margin-mobile": "0.75rem",
        "space-xs": "0.25rem",
        gutter: "1rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        margin: "1.5rem",
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "headline-xl": ["Plus Jakarta Sans"],
        "label-lg": ["Inter"],
        "metric-mono-sm": ["JetBrains Mono"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-xl-mobile": ["Plus Jakarta Sans"],
        "metric-mono-lg": ["JetBrains Mono"],
        "headline-lg": ["Plus Jakarta Sans"],
        "label-md": ["Inter"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-lg": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "500" }],
        "metric-mono-sm": ["11px", { lineHeight: "14px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "metric-mono-lg": ["14px", { lineHeight: "18px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-md": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg-mobile": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
